---
title: "Survey Methodology"
output: html_document
---

### Surveying Burnout  

There are a variety of valid and reliable instruments to measure burnout as described by the [National Academy of Medicine](https://nam.edu/valid-reliable-survey-instruments-measure-burnout-well-work-related-dimensions/). Below is a description of a variety of survey methods that have been researched for different purposes. This culmination of multiple surveys is chose the best survey for the purpose of gathering data from this specific community.   

## Maslach Burnout Inventory   

The Laslach Burnout Inventory survey is used mainly to measure burnout in individuals working in human services and medical professions. This survey is about 22 items that cover three areas; Emotional Exhaustion, Depresonalization and low sense of personal accomplishment. Each subscale includes multiple questions with frequency rating choices of: Never, A few times a year or less, Once a month or less, A few times a month, Once a week, A few times a week, or Every day.  

Tthe rights to use this survey method are not free and survey questions were geared specifically towards professionals in human services and medical professions.  

## Oldenburg Burnout Inventory  

This survey is 16-item survey with positively and negatively framed tems that cover two areas of burnout: exhaustion (physical, cognitive, and affective aspects) and disengagement from work (negative attitudes toward work objects, work content or work in general). There are multiple questions for each of these subsections and the responses are in the form of a 4 point Likert scale from strongly agree (1) to strongly disagree (4).  

This survey method cost no money and the instrument is publicly available for use. The survey is also valid and reliable in adult age groups in any occupation.  

## Copenhagen Burnout Inventory  

The purpose of the Copenhagen Burnout Inventory is to aimed at gathering data regarding 3 areas: personal (degree of physical and psychological fatigue and exhaustion), work (degree of physical and psychological fatigue and exhaustion related to work), and client-related (or a similar term such as patient, student, etc.) burnout.  

This 19-item survey is broken down into these three groups: 
* Overall physical and psychological fatigue: 6 items. 
* Physical and psychological fatigue related to work: 7 items. 
* Client-related burnout: 6 items. 

This survey is free for public use. 